name: data_flow
version: 1.0.0
config-version: 2

profile: data_flow

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  data_flow:
    +materialized: table
