data_flow:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: "{{ env_var('DBT_CLICKHOUSE_HOST', 'clickhouse') }}"
      port: "{{ env_var('DBT_CLICKHOUSE_PORT', '8123') | int }}"
      user: "{{ env_var('DBT_CLICKHOUSE_USER', 'analytics') }}"
      password: "{{ env_var('DBT_CLICKHOUSE_PASSWORD', 'analytics') }}"
      secure: false
      verify: false
      database: "{{ env_var('DBT_CLICKHOUSE_DB', 'analytics') }}"
      schema: "{{ env_var('DBT_CLICKHOUSE_DB', 'analytics') }}"
